### ISSUE TITLE
Minimum Viable Product - Add form functionality to challenge creation page

### ISSUE THREAD

**Issue by RedBlueCarrots** [RedBlueCarrots/WikiPath#13]
This script will provide functionality to the challenge creation page

Will just involve filling in a form, passing off the information to a server, and redirecting back to the home screen if an OK is received from the server.

Requires https://github.com/RedBlueCarrots/WikiPath/issues/9 to be completed before hand, #26  to have done the creation page.

**Comment by RadiationOcelot** [comment]
Completed [here](https://github.com/RedBlueCarrots/WikiPath/pull/48). Will close the issue.
