### ISSUE TITLE
Minimum Viable Product - Render challenges and submissions in challenge view page

### ISSUE THREAD

**Issue by RedBlueCarrots** [RedBlueCarrots/WikiPath#14]
The challenge view page needs to:
Display contents based off the clicked on challenge prior
Display the submissions either:
Your submitted attempt (if the challenge is still going)
All submitted attempts (if the challenge is finished)

**Comment by DeltaO3** [comment]
Gonna rename this issue to dealing with rendering the view page properly.

**Comment by RedBlueCarrots** [comment]
Done with #12
