### ISSUE TITLE
Minimum Marketable Product - Wikipedia API path Verification

### ISSUE THREAD

**Issue by RadiationOcelot** [RedBlueCarrots/WikiPath#18]
We need to create a server that can connect to the Wikipedia API to:

- Determine if an article given by the user is valid
- Confirm that a path given by a user from one article form another is possible

This is most likely going to be implemented as functions that can be called by the server program.

**Comment by RedBlueCarrots** [comment]
Going to split this issue with #50, renaming

**Comment by RedBlueCarrots** [comment]
Consider extending the wikipedia.py file added in https://github.com/RedBlueCarrots/WikiPath/pull/55 

https://www.mediawiki.org/w/api.php?action=help&modules=query%2Blinks

Consider using this part of the api

**Comment by jaidan18** [comment]
Should invalid paths still submit and be recorded as wrong, or should they not submit at all?

We could also make this a setting in the challenge creation page.

**Comment by RedBlueCarrots** [comment]
It should be similar to what currently happens with article verification, it should "submit" but fail verification, and the webpage should reload and include errors below the articles which don't have a correct link
