### ISSUE TITLE
Minimum Marketable Product - Server creation and HTTP call handling

### ISSUE THREAD

**Issue by RadiationOcelot** [RedBlueCarrots/WikiPath#19]
The server that [queries the database](https://github.com/RedBlueCarrots/WikiPath/issues/10), [calls the Wikipedia API](https://github.com/RedBlueCarrots/WikiPath/issues/18), and [deals with the HTTP calls from front end](https://github.com/RedBlueCarrots/WikiPath/issues/9) has to be developed.

This will most likely be developed alongside the databases and functions that call the Wikipedia API.

**Comment by RedBlueCarrots** [comment]
what is the point of this one?

**Comment by RadiationOcelot** [comment]
This was back when all of the issues were created and there was no one issue that was "create all of the server." I don't think this is needed though since we've already done it in the MVP.

**Comment by DeltaO3** [comment]
Agree, happy to close it
