### ISSUE TITLE
 Fill in the ReadMe file

### ISSUE THREAD

**Issue by DeltaO3** [RedBlueCarrots/WikiPath#2]
From the project brief: 

1. a description of the purpose of the application, explaining the its design and use.
2. a table with with each row containing the i) UWA ID ii) name and iii) Github user name of the group members.
3. a brief summary of the architecture of the application.
4. instructions for how to launch the application.
5. instructions for how to run the tests for the application.

**Comment by RadiationOcelot** [comment]
I'm going to remove this issue from the MVP milestone as this is something that will be ongoing and updated throughout the project as we include more dependencies.

**Comment by RadiationOcelot** [comment]
Throughout the project, the ReadMe has been updated constantly, and I believe we don't need to update it anymore. Closing this issue.
