### ISSUE TITLE
Minimum viable product - create template for challenge submission

### ISSUE THREAD

**Issue by DeltaO3** [RedBlueCarrots/WikiPath#25]
As per title, we want a template for challenge submission
This is accessed when a user chooses to submit a challenge. 
as per #4 : 
-  List of text input boxes (which may be templates in and of themselves?)
- submission button

This template may wish to extend the template for challenge view
Functionality (submission doing anything) is not required for this issue.

**Comment by RadiationOcelot** [comment]
Completed [here.](https://github.com/RedBlueCarrots/WikiPath/pull/44) I'll close this issue.
