### ISSUE TITLE
Minimum viable product - edit flask routing

### ISSUE THREAD

**Issue by DeltaO3** [RedBlueCarrots/WikiPath#27]
routes.py should have links to each different page. This should be done once / as templates are created.
Editing the navbar file/s may also be required, along with any other templates that provide links.

This will enable proper navigation between pages.

**Comment by RedBlueCarrots** [comment]
Unassigning myself from this - I think this is just an issue worth checking in relevant PRs for new pages

**Comment by DeltaO3** [comment]
Agree, gonna close this issue as irrelevent.
