### ISSUE TITLE
Minimum Viable Product - Draw up finalised, agreed upon mockups

### ISSUE THREAD

**Issue by DeltaO3** [RedBlueCarrots/WikiPath#30]
As a team we have realised that we have a variety of ideas of what the project looks like despite a planning phase, resulting in redundant issues, redundant work and overall confusion.
We want a finalised mockup and flow of the project.

These can be as any file format, but for now, place them in a folder in the outer directory.

**Comment by RedBlueCarrots** [comment]
I hadn't thought of it like that before, i'd always envisioned 2 pages, but 1 does make sense. Happy with these mockups

**Comment by RadiationOcelot** [comment]
Great! I'll make a document with these mockups in it and I'll close the issue!

**Comment by RadiationOcelot** [comment]
Unified document link is here: https://docs.google.com/document/d/1YvWscxkJtEEeX7Hz1wcXsf8wgMO-ksFzvSnp9jR2ddI/edit?usp=sharing

I'm going to close this issue, but if we ever need to adjust something, then we can always open up another issue and modify this document.
