### ISSUE TITLE
Minimum Marketable Product - Challenge Completion Handling

### ISSUE THREAD

**Issue by RedBlueCarrots** [RedBlueCarrots/WikiPath#53]
On the server, logic will need to be created to handle the completion of a challenge

This will include awarding points for winning entries, changing the state of the challenge in the database, and figuring out how to automatically run this logic - potentially check every minute, or whenever the database is queried.

Might also be worth adding checks to current submission attempts to block attempts which are after a challenge has been finished

**Comment by RadiationOcelot** [comment]
Completed here #63
