### ISSUE TITLE
Bug fixing - Login modal

### ISSUE THREAD

**Issue by DeltaO3** [RedBlueCarrots/WikiPath#59]
If you get an error, and then close the modal, the error is still there when opening the modal.

May be more difficulty then its worth. (bug or feature?)

Pressing enter on the login form defaults to "Create account" as oppose to login.

**Comment by RedBlueCarrots** [comment]
> If you get an error, and then close the modal, the error is still there when opening the modal.
> 
> May be more difficulty then its worth. (bug or feature?)

I reckon this is undesirable behaviour, will remove
